definitions:
  github_com_bytesByHarsh_go-my-info_internal_database.BankType:
    enum:
    - central
    - cooperative
    - commercial
    - regional
    - local
    - specialized
    - small_finance
    - payments
    type: string
    x-enum-varnames:
    - BankTypeCentral
    - BankTypeCooperative
    - BankTypeCommercial
    - BankTypeRegional
    - BankTypeLocal
    - BankTypeSpecialized
    - BankTypeSmallFinance
    - BankTypePayments
  github_com_bytesByHarsh_go-my-info_models.PaginatedListResp-models_Bank:
    properties:
      data:
        items:
          $ref: '#/definitions/models.Bank'
        type: array
      has_more:
        type: boolean
      items_per_page:
        type: integer
      page:
        type: integer
      total_count:
        type: integer
    type: object
  github_com_bytesByHarsh_go-my-info_models.PaginatedListResp-models_BankAccount:
    properties:
      data:
        items:
          $ref: '#/definitions/models.BankAccount'
        type: array
      has_more:
        type: boolean
      items_per_page:
        type: integer
      page:
        type: integer
      total_count:
        type: integer
    type: object
  github_com_bytesByHarsh_go-my-info_models.PaginatedListResp-models_User:
    properties:
      data:
        items:
          $ref: '#/definitions/models.User'
        type: array
      has_more:
        type: boolean
      items_per_page:
        type: integer
      page:
        type: integer
      total_count:
        type: integer
    type: object
  models.AddBankAccountReq:
    properties:
      account_number:
        type: string
      account_type:
        type: string
      balance:
        type: string
      bank_id:
        type: string
      currency:
        type: string
      name:
        type: string
    required:
    - account_number
    - account_type
    - balance
    - bank_id
    - currency
    - name
    type: object
  models.AuthReq:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  models.AuthResp:
    properties:
      access_token:
        type: string
    type: object
  models.Bank:
    properties:
      address:
        type: string
      bank_type:
        $ref: '#/definitions/github_com_bytesByHarsh_go-my-info_internal_database.BankType'
      contact_email:
        type: string
      contact_phone:
        type: string
      created_at:
        type: string
      established_year:
        type: integer
      id:
        type: string
      name:
        type: string
      updated_at:
        type: string
    type: object
  models.BankAccount:
    properties:
      account_number:
        type: string
      account_type:
        type: string
      balance:
        type: string
      created_at:
        type: string
      currency:
        type: string
      id:
        type: string
      name:
        type: string
      updated_at:
        type: string
    type: object
  models.CreateBankReq:
    properties:
      address:
        type: string
      bank_type:
        $ref: '#/definitions/github_com_bytesByHarsh_go-my-info_internal_database.BankType'
      contact_email:
        type: string
      contact_phone:
        type: string
      established_year:
        type: integer
      name:
        type: string
    required:
    - address
    - bank_type
    - contact_email
    - established_year
    - name
    type: object
  models.CreateUserByAdminReq:
    properties:
      email:
        type: string
      is_active:
        type: boolean
      is_superuser:
        type: boolean
      name:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - is_active
    - name
    - password
    - username
    type: object
  models.CreateUserReq:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - name
    - password
    - username
    type: object
  models.JSONResp:
    properties:
      data: {}
      message:
        type: string
      status:
        type: string
    type: object
  models.JSONerrResponse:
    properties:
      error:
        type: string
    type: object
  models.UpdateBankAccountReq:
    properties:
      account_number:
        type: string
      account_type:
        type: string
      balance:
        type: string
      currency:
        type: string
      name:
        type: string
    required:
    - account_number
    - account_type
    - balance
    - currency
    - name
    type: object
  models.UpdatePasswordReq:
    properties:
      password:
        type: string
    required:
    - password
    type: object
  models.UpdateUserReq:
    properties:
      email:
        type: string
      name:
        type: string
      phone_num:
        type: string
      profile_img:
        type: string
      username:
        type: string
    required:
    - email
    - name
    - phone_num
    - profile_img
    - username
    type: object
  models.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      is_active:
        type: boolean
      is_superuser:
        type: boolean
      name:
        type: string
      phone_number:
        type: string
      profile_img:
        type: string
      role:
        type: integer
      updated_at:
        type: string
      username:
        type: string
    type: object
info:
  contact:
    email: harshmittal2210@gmail.com
    name: Harsh Mittal
paths:
  /:
    get:
      description: get string by ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.JSONResp'
      summary: Hello API
      tags:
      - Ping
  /accounts/:
    get:
      consumes:
      - application/json
      description: get all bank account
      parameters:
      - description: Page Number
        in: query
        name: page
        required: true
        type: integer
      - description: Items Per Page
        in: query
        name: items_per_page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_bytesByHarsh_go-my-info_models.PaginatedListResp-models_BankAccount'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.JSONerrResponse'
      summary: Get All Account
      tags:
      - Bank Accounts
    post:
      consumes:
      - application/json
      description: create new bank account
      parameters:
      - description: Bank Account Body
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/models.AddBankAccountReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.BankAccount'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.JSONerrResponse'
      summary: Create Account
      tags:
      - Bank Accounts
  /accounts/{account_id}:
    get:
      consumes:
      - application/json
      description: get bank account details
      parameters:
      - description: Bank Account ID
        in: path
        name: account_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.BankAccount'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.JSONerrResponse'
      summary: Get Account
      tags:
      - Bank Accounts
    put:
      consumes:
      - application/json
      description: update bank account details
      parameters:
      - description: Bank Account ID
        in: path
        name: account_id
        required: true
        type: string
      - description: Bank Account Body
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/models.UpdateBankAccountReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.JSONerrResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.JSONerrResponse'
      summary: Update Account
      tags:
      - Bank Accounts
  /banks/list:
    get:
      consumes:
      - application/json
      description: get all bank list
      parameters:
      - description: Page Number
        in: query
        name: page
        required: true
        type: integer
      - description: Items Per Page
        in: query
        name: items_per_page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_bytesByHarsh_go-my-info_models.PaginatedListResp-models_Bank'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.JSONerrResponse'
      summary: Get Bank List
      tags:
      - Bank
  /banks/register:
    post:
      consumes:
      - application/json
      description: create a new bank
      parameters:
      - description: Create Bank Body
        in: body
        name: page
        required: true
        schema:
          $ref: '#/definitions/models.CreateBankReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Bank'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.JSONerrResponse'
      summary: Create Bank
      tags:
      - Bank
  /users/{username}:
    delete:
      consumes:
      - application/json
      description: delete user from db by admin
      parameters:
      - description: Username
        in: path
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.JSONerrResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.JSONerrResponse'
      summary: Delete user from DB
      tags:
      - Users
    get:
      consumes:
      - application/json
      description: get another user details
      parameters:
      - description: Username
        in: path
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.JSONerrResponse'
      summary: Get User
      tags:
      - Users
    post:
      consumes:
      - application/json
      description: create new user by admin
      parameters:
      - description: Username
        in: path
        name: username
        required: true
        type: string
      - description: User Body
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UpdateUserReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.JSONerrResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.JSONerrResponse'
      summary: Create User By Admin
      tags:
      - Users
  /users/add:
    post:
      consumes:
      - application/json
      description: create new user by admin
      parameters:
      - description: User Body
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.CreateUserByAdminReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.JSONerrResponse'
      summary: Create User By Admin
      tags:
      - Users
  /users/list:
    get:
      consumes:
      - application/json
      description: user list
      parameters:
      - description: Page Number
        in: query
        name: page
        required: true
        type: integer
      - description: Items Per Page
        in: query
        name: items_per_page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_bytesByHarsh_go-my-info_models.PaginatedListResp-models_User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.JSONerrResponse'
      summary: Get User List
      tags:
      - Users
  /users/login:
    post:
      consumes:
      - application/json
      description: get login token
      parameters:
      - description: Login Body
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/models.AuthReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.AuthResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.JSONerrResponse'
      summary: Login User
      tags:
      - Authentication
  /users/me:
    delete:
      consumes:
      - application/json
      description: delete user
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.JSONerrResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.JSONerrResponse'
      summary: Delete user
      tags:
      - Users
    get:
      consumes:
      - application/json
      description: get user details
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.JSONerrResponse'
      summary: Get User
      tags:
      - Users
    put:
      consumes:
      - application/json
      description: update user details
      parameters:
      - description: User Body
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UpdateUserReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.JSONerrResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.JSONerrResponse'
      summary: update User
      tags:
      - Users
  /users/me/password:
    put:
      consumes:
      - application/json
      description: update user password
      parameters:
      - description: Password Body
        in: body
        name: password
        required: true
        schema:
          $ref: '#/definitions/models.UpdatePasswordReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.JSONerrResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.JSONerrResponse'
      summary: Update User Password
      tags:
      - Users
  /users/register:
    post:
      consumes:
      - application/json
      description: create new user
      parameters:
      - description: User Body
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.CreateUserReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.JSONerrResponse'
      summary: Create User
      tags:
      - Users
swagger: "2.0"
